# Streamlit theme - EXACT match to Figma design system
# Source: https://www.figma.com/make/nI65iKCEyzqO5dfqb3fXsL/FA-Job-Importer-Design-System

[theme]
primaryColor = "#3b82f6"          # --primary: Blue from Figma
backgroundColor = "#fafafa"        # --background: Light gray from Figma
secondaryBackgroundColor = "#f1f5f9"  # --secondary/muted: Lighter gray for cards
textColor = "#1a1a1a"             # --foreground: Near black from Figma
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true
enableCORS = true
enableXsrfProtection = true
