[server]
baseUrlPath = "/"
enableCORS = false
enableXsrfProtection = true
headless = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#366092"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

